### ISSUE TITLE
unable to post to monger google group,no reposne on irc or to emails to ClojureWerkz

### ISSUE THREAD

**Issue by ShayMatasaro** [michaelklishin/monger#110]
Hi,

Is this project alive?

The google group is moderated and non of my posts gets published.

There is  no response on freenode #ClojureWerkz.

no response when mailing contact@clojurewerkz.org

Thanks,

**Comment by michaelklishin** [comment]
[It is alive](https://github.com/michaelklishin/monger/commits/master). Yes, the group uses moderation. IRC channel hasn't been active for a while because we don't have the time to hang out there.
