### ISSUE TITLE
If slash is present in the keyword, it doesn't persist properly in db

### ISSUE THREAD

**Issue by rijuzoomo** [michaelklishin/monger#113]
I have observed this behavior while using find-and-modify and update functions. When slash is present in the keyword name, the part before the slash gets erased in db.

Ran the following commands in repl:-
(def x (keyword "AB/CD something"))
(mc/find-and-modify db coll query {$set {:example {x true}}} {:return-new true})
 
Output:
{:example {:CD something true}, <other_fields>}

DB:
{ <other_fields>
"example" : {
         "CD something" : true
},
<other_fields>
}

Monger Version : 3.0.0
clojure version 1.6.0
Lein version Leiningen 2.5.1 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM
MongoDB version 3.0.2

**Comment by michaelklishin** [comment]
That's why keywords should be used with care. Sorry, not interested in fixing edge cases with keywords.

**Comment by michaelklishin** [comment]
Here's what's going on:

``` clojure
(name :a/b)
;= "b"
```

Yeah, I'm not going to reinvent `clojure.core/name` to support this stuff.

**Comment by rijuzoomo** [comment]
Thanks for the info
