### ISSUE TITLE
Documentation: how to disable log messages from the driver

### ISSUE THREAD

**Issue by boechat107** [michaelklishin/monger#115]
Would it be a good idea to include in the documentation a reference to [the solution](https://groups.google.com/d/msg/mongodb-user/_t5rHlaxYxI/aNdlMVIrcR0J)? I spent some hours looking for it...

At least for me, including a new dependency (`[org.slf4j/slf4j-nop "1.7.12"]`) to disable logging messages is a little unusual.

**Comment by michaelklishin** [comment]
@boechat107 feel free to submit a PR.

**Comment by boechat107** [comment]
OK, it's done. See [PR#116](https://github.com/michaelklishin/monger/pull/116).

**Comment by michaelklishin** [comment]
https://github.com/clojurewerkz/monger.docs/issues/20 is live.

**Comment by ioRekz** [comment]
So if I understand correctly 
[org.slf4j/slf4j-api "1.7.12"]
and                
 [org.slf4j/slf4j-nop "1.7.12"]
should get rid of mongo driver logging ?

I still have them

**Comment by michaelklishin** [comment]
@ioRekz see https://github.com/michaelklishin/monger/pull/116/files. SLF4J can be configured using a properties file, too. Monger would rather stay away from providing an SLF4J interface in any capacity.

**Comment by ioRekz** [comment]
Yes I saw this PR but adding [org.slf4j/slf4j-nop "1.7.12"] to the deps does not disable mongo log messages

**Comment by michaelklishin** [comment]
"multiple SLF4J bindings" means "multiple implementations", so only one of them is actually used

**Comment by ioRekz** [comment]
Ok I went with a logback config disabling some logs on the mongo namespace.
Thanks

**Comment by jdkealy** [comment]
Hey, could someone explain how to go with a logback config? I too added to my project and the logs are unchanged.

**Comment by njj** [comment]
For those looking for a little more insight on how to accomplish this, I found this resource:

https://github.com/vaughnd/clojure-example-logback-integration

I added the required deps to my project.clj and copy and pasted the logback file from this repo into my `/src` directory.  I removed the stdout from the debug level:

```
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>
    <logger name="org.mongodb" level="WARN"/>
    <root level="DEBUG">
    </root>
</configuration>
```

**Comment by zendevil** [comment]
I followed the documentation and added [org.slf4j/slf4j-nop "1.7.12"] in my project.clj as a dependency, but I still see the logs.
