### ISSUE TITLE
Less verbose syntax for multiple connection methods

### ISSUE THREAD

**Issue by jacobemcken** [michaelklishin/monger#117]
Using Monger when authenticating feels bulky when wanting to support multiple ways to connect to the database like:

  * without user/password
  * provide host and port
  * provide both host and user/password
  * provide all: host, port, user and password

For every project where I use Monger I usually create something like the following to allow all these combinations:

``` clojure
(defn auth
  [{:keys [db auth-db user pwd host port] :as config}]
  (if (some empty? [user pwd])
    (mongo/connect (select-keys config [:host :port]))
    (let [creds (monger.credentials/create user (or auth-db db) pwd)]
      (if port
        (mongo/connect-with-credentials host port creds)
        (mongo/connect-with-credentials host creds)))))
```

Mainly the fact that `connect` takes a map and `connect-with-credentials` takes individual parameters for host and port feels out of place. I might be overlooking something ie. like when connecting to a replica set (I myself only ever used Monger for connecting to a single Mongo instance). I don't mind doing a PR but let me know if you are interested and ie. if there are any pitfalls I should look out for.

**Comment by michaelklishin** [comment]
This API has been around for a very long time. I'm not a fan of it but it's not easy to come up with something compatible and support the many options MongoDB Java driver has.

This is the first time someone complained about this. I'll leave the issue open in case someone wants to suggest anything specific. My primary goal is to not break the API if I can.

**Comment by jacobemcken** [comment]
I understand your concern and I'm not interested in taking the whole thing apart :smile:
I'll let you know if time and reading up on Monger (and the Java driver), will give me enough insight to actually come up with a specific suggestion.

**Comment by jacobemcken** [comment]
Suggestion: being able to represent connection parameters as Clojure core data structures.

This would allow for easily storing connection configuration in formats like edn and yaml even for replica sets and lists of credentials without having to post process them to get Mongo driver friendly objects like `ServerAddress`, `List<ServerAddress>`, `List<MongoCredential>` and `MongoClientOptions`.

A `ServerAddress` could be represented by a vector:
  * `["mongodb.domain.com"]` - would use default MongoDB port
  * `[27018]` - would use default ip
  * `["mongodb.domain.com" 27018]`

Both `MongoCredential` and `MongoClientOptions` should be represented by a map. The different credentialtypes could be represented by a map key ie. `:type "x509"`. Also some of the options doesn't use primitive types which might be hard or even impossible to support.

But I imagine something along the lines:
```
  (connect)
  (connect "server1.mydomain.com")
  (connect 27035)
  (connect ["server1.mydomain.com" 27035])
  (connect [["server1.mydomain.com"] ["server2.mydomain.com"]]) ; this automatically identifies a list of addresses and initializes `MongoClient using List<ServerAddress>`
  (connect [["server1.mydomain.com" 27035] ["server2.mydomain.com"]])
  (connect ["server1.mydomain.com" 27035] {:max-wait-time 200000 :write-concern :replicas-safe})
  (connect ["server1.mydomain.com" 27035] {:max-wait-time 200000} {:user "admin" :password "Je3%/kiibzmQw34" :auth-db "admin"})
  (connect ["server1.mydomain.com" 27035] {:max-wait-time 200000} [{:type "x509" :user "admin"} {:user "admin2" :password "some other pw" :auth-db "admin"}])
  (connect ["server1.mydomain.com" 27035] nil {::user "admin" :password "Je3%/kiibzmQw34" :auth-db "admin"})
```

Would a further discussion and work on something like the above be of any interest?

**Comment by michaelklishin** [comment]
Nested vectors and this many overloads look worse than what we have at the moment.

**Comment by michaelklishin** [comment]
I'm not convinced that the provided version is less verbose. What we have is not idea but most people don't mind it. We'll see if a better idea comes down the road.
