### ISSUE TITLE
monger util object-id and random-uuid invalid objectid

### ISSUE THREAD

**Issue by ioRekz** [michaelklishin/monger#123]
When I use
(object-id (random-uuid))
I have this error :
invalid hexadecimal representation of an ObjectId: [48c2a0c6-d90f-4254-9132-c3d2e344d850]

What is the preferred way to generate random object ids ?
I'm using monger 3.0.1

**Comment by michaelklishin** [comment]
Please ask questions on the mailing list.

`monger.util/random-uuid` generates a UUID (using `java.util.UUID`), not a BSON Object ID or string. You can use UUIDs converted to strings as object IDs. Instantiating `ObjectId` using Java interop will produce an object ID which has a generated component. `monger.util/object-id` does that but assumes you use a string (when arity-1 is used).
