### ISSUE TITLE
`monger.core/authenticate` does not exist

### ISSUE THREAD

**Issue by fhur** [michaelklishin/monger#128]
The `monger.core/authenticate` function specified in the getting [started > authentication](http://clojuremongodb.info/articles/getting_started.html#authentication) section does not exist. Am I missing something? I'm using `[com.novemberain/monger "3.0.2"]`

**Comment by michaelklishin** [comment]
[New authentication API](https://github.com/michaelklishin/monger/blob/master/ChangeLog.md#new-authentication-api). Feel free to [submit a doc guide correction](https://github.com/clojurewerkz/monger.docs).

**Comment by tirkarthi** [comment]
`for` shown in the new authentication API has been renamed to `create` as per the commit at https://github.com/michaelklishin/monger/commit/4ff7d05aa4d9a84d5e3a7db2b6d65182f7cc767e

**Comment by tirkarthi** [comment]
Created a doc fix PR at https://github.com/clojurewerkz/monger.docs/pull/24 . But the `authenticate` function used to return true or false meanwhile the new credentials based authentication returns a `MongoClient` object or `MongoCommandException` on failure. I hope its a breaking change. Kindly add in if I am missing anything.

Thanks a lot for the work on monger.

**Comment by michaelklishin** [comment]
Seems to be addressed in https://github.com/clojurewerkz/monger.docs/pull/24.
