### ISSUE TITLE
Support for readConcern settings

### ISSUE THREAD

**Issue by ghost** [michaelklishin/monger#130]
MongoDB 3.2 [added support for a readConcern setting](https://docs.mongodb.org/manual/release-notes/3.2/#readconcern) that supports "local" and "majority" values (and perhaps others in the future).

A cursory look at the code suggests that Monger doesn't support this setting.

**Comment by leoshaw** [comment]
Looks as though this was added in 3.1.0 https://github.com/michaelklishin/monger/commit/ccffffc9125dcdcf305f98a1259a1b7dbec29e73 - if you're using the options to set the write concern too then you may need to call `set-default-write-concern!` instead as I think the option is effectively ignored.

**Comment by michaelklishin** [comment]
Seems to be addressed in ccffffc9125dcdcf305f98a1259a1b7dbec29e73, the write concern comment has a separate issue: #146.
