### ISSUE TITLE
GridFS call to find-map-by-id results in ClassCastException

### ISSUE THREAD

**Issue by tuhlmann** [michaelklishin/monger#131]
I'm trying to read a GridFS file like so (Monger 3.0.2):

```
  (let [db (db/get-db)
        fs (get-gridfs db)]
    (gfs/find-map-by-id fs id)))
```
`id` is of type ObjectId. The resulting exception is:

`org.bson.types.ObjectId cannot be cast to com.mongodb.DBObject`

I think the problem comes from this function and also `find-by-id` calling `find-one` which expects a query without changing `id` into a query.

A workaround is to call `find-one` directly:

```
gfs/find-one-as-map fs {:_id id}
```

**Comment by michaelklishin** [comment]
What what "this function?

Please post the entire stack trace.

**Comment by tuhlmann** [comment]
@michaelklishin Ah sorry. `this function` is `find-one`, it expects a query and just gets an id from `find-by-id` or `find-map-by-id`.

I paste the stack trace later today if you still need it, I need to break it again :)

**Comment by tuhlmann** [comment]
@michaelklishin  Here's the stacktrace I get for this call `(gfs/find-map-by-id fs id)`:

```
numerix.model.files/get-file       files.clj:   17
monger.gridfs/find-map-by-id     gridfs.clj:  191
monger.gridfs/find-one               gridfs.clj:  175
java.lang.ClassCastException: org.bson.types.ObjectId cannot be cast to com.mongodb.DBObject
```

Contrary to my former statement a call to  `(gfs/find-by-id fs id)` works fine.

**Comment by michaelklishin** [comment]
@tuhlmann if you think it is a bug in `monger.gridfs`, please submit a PR (with some test cases)
