### ISSUE TITLE
mongo-options-builder broken when supplying auto-connect-retry option

### ISSUE THREAD

**Issue by jnape** [michaelklishin/monger#137]
In version 3.0.2, `monger.core/mongo-options-builder` tries to invoke `.autoConnectRetry` on an instance of `com.mongodb.MongoClientOptions.Builder`, which is a non-existent method. But it gets worse.

Up in the arguments vector, we see this:

```clojure
[{:keys [connections-per-host threads-allowed-to-block-for-connection-multiplier
           max-wait-time connect-timeout socket-timeout socket-keep-alive auto-connect-retry max-auto-connect-retry-time
           description write-concern cursor-finalizer-enabled read-preference
           required-replica-set-name] :or [auto-connect-retry true]}]
```

Paying particular attention to `:or [auto-connect-retry true]`, we notice that this isn't actually valid Clojure, which is to say it's not doing anything; it seems like it was intending to be `{auto-connect-retry true}` (notice the map literal vs vector), although ironically, this is saving people who aren't specifying `auto-connect-retry` from entering a code path that ultimately results in a compiler exception.

Ironically, the `autoConnectRetry` facility in `com.mongodb.MongoClientOptions` has been removed, citing confusion as the cause for deprecation, so the right thing here is to just remove the code paths associated with both `autoConnectRetry` and `maxAutoConnectRetryTime` (also a non-existent method).

**Comment by puredanger** [comment]
Note that Clojure 1.9.0-alpha11 now has specs for clojure.core that cause this syntax error to fail at compile time. This seems to be fixed in master, but no newer release is available.

**Comment by michaelklishin** [comment]
https://github.com/michaelklishin/monger/commit/ccffffc9125dcdcf305f98a1259a1b7dbec29e73 addresses this as far as I can tell.
