### ISSUE TITLE
Recommended way to maintain a connection in a long session

### ISSUE THREAD

**Issue by vspinu** [michaelklishin/monger#138]
Hi and thanks for the excellent library!

What is the recommended way to define a connection within a long running clojure application?  The basic `(defonce conn (mg/connect))` looks too basic to be true.

Thanks.

**Comment by michaelklishin** [comment]
Use Component, not vars. Please ask questions on the mailing list in the future.

**Comment by vspinu** [comment]
Thanks. For the reference, [Component](https://github.com/stuartsierra/component) and ready made [components for monger](https://github.com/danielsz/system/blob/master/src/system/components/mongo.clj) as part of [system](https://github.com/danielsz/system).
