### ISSUE TITLE
find-one-as-map returns _id field when loading a subset of fields

### ISSUE THREAD

**Issue by chinmaydd** [michaelklishin/monger#139]
`find-one-as-map` returns `_id` field even when you don't ask for it.

```clojure
user=> (mc/find-one-as-map db "users" {:username "user1"} ["email"])
{:email => "user1@hotmail.com", :_id #object[org.bson.types.ObjectId 0x3f278a23 "5771ae093180246df93c574d"]}
```

Wouldn't it be better if we only have the fields which we requested for returned?

**Comment by michaelklishin** [comment]
All DB objects loaded by the Java driver carry ids on them. It makes sense since very often you need that information to do anything with the object.
