### ISSUE TITLE
How can I run an aggregation pipeline query that contains function calls?

### ISSUE THREAD

**Issue by camsaul** [michaelklishin/monger#143]
Hi, great library! I want to use `monger.collection/aggregate` to run a query that contains function calls, like this:

```json
[
  {
    "$match": {
      "hour": {
        "$gte": ISODate("2016-08-09T00:00:00Z")
      }
    }
  },
  {
    "$group": {
      "_id": {
        "year": {"$year": "$hour"},
        "month": {"$month": "$hour"}
      },
      "count": {
        "$sum": "$count"
      }
    }
  }
]
```

Does Monger support any special way of making function calls like these, perhaps like HoneySQL's `call` or Korma's `sqlfn`? Or is there any to pass a raw String containing the query to `aggregate`? We use Monger as part of [Metabase](http://github.com/metabase/metabase) and let people write raw MongoDB aggregation pipeline queries but we're running into issues when people write queries like the one above because they can't be parsed as JSON.

Any suggestions or ideas on how to work around this would be greatly appreciated.

**Comment by michaelklishin** [comment]
There is nothing like `sqlfn`.

**Comment by camsaul** [comment]
@michaelklishin, lack of support for functions like these are a legitimate issue that affects the usability of Monger; effectively it means Monger only supports a subset of valid queries. Does it make sense to leave this as an open issue that can perhaps be addressed by a community-sourced PR?

**Comment by michaelklishin** [comment]
@camsaul it can be claimed that lack of X is a serious issue and should be open but this is the first time I hear about it and Monger is 5 years old.

If someone wants to contribute, they can, or they can create a separate project that solves it. I'm not interested in having open issues for every thinkable thing that is missing. This was a question, and I never use GitHub issues for questions, so I closed it.
