### ISSUE TITLE
IllegalStateException: state should be: open

### ISSUE THREAD

**Issue by expez** [michaelklishin/monger#145]
I get the following exception while slurping a large amount of data, across multiple databases:

```
                                          com.mongodb.DBCursor.hasNext                 DBCursor.java:  155
                                    com.mongodb.MongoBatchCursorAdapter.hasNext  MongoBatchCursorAdapter.java:   46
                                 com.mongodb.operation.QueryBatchCursor.hasNext         QueryBatchCursor.java:  103
                                 com.mongodb.operation.QueryBatchCursor.getMore         QueryBatchCursor.java:  205
com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection           ClusterBinding.java:   86
                             com.mongodb.connection.DefaultServer.getConnection            DefaultServer.java:   84
                                       com.mongodb.assertions.Assertions.isTrue               Assertions.java:   70
java.lang.IllegalStateException: state should be: open
```

I've googled this error furiously and it looks like this happens when someone (usually by accident, and in some other thread) calls `.close` on the `MongoClient`.  I call Monger's `disconnect` as part of shutting down my app, but nowhere else...

I have a single `conn` which is shared across threads, but other than some initial book keeping to get in sync, no other thread uses mongo while this initial slurp happens, and they certainly aren't actively closing any connections.

Have you seen this before?  What could be causing this?

**Comment by expez** [comment]
I can replicate this error by calling `(.close conn)` in another thread.  As to what might be causing this I'm still drawing a blank.

**Comment by michaelklishin** [comment]
Concurrent connection closure is likely not supported by the Java client. Monger adds nothing new on top of that.

**Comment by expez** [comment]
Why did you close this?  My app does not close any connections, yet the connections get closed, and failure ensues.

**Comment by michaelklishin** [comment]
Monger does not either.
