### ISSUE TITLE
Write concern specified in options is ignored

### ISSUE THREAD

**Issue by leoshaw** [michaelklishin/monger#146]
If you call `connect` passing in options including a write concern, the write concern isn't respected.  E.g.

```
  (let [connection (mg/connect 
                     (mg/server-address("localhost")) 
                     (mg/mongo-options {:write-concern WriteConcern/MAJORITY}))
        database (mg/get-db connection "db-name")]
    (mc/upsert database "collection" {:id "id"} {:id "id", :name "Bob"}))
```

(excuse the beginner clojure!)

The update happens with monger's default write concern `WriteConcern/ACKNOWLEDGED`.  Although it's easy to work around by calling `set-default-write-concern!`, or specifying the write concern on the upsert, this probably isn't what the client expects: if `mongo-options` accepts the write concern then it should be respected over the default.  

In our codebase this also led to the read concern being set as intended (majority) but the write concern defaulting to acknowledged, which had interesting results.

**Comment by Freezystem** [comment]
- First, there is a typo line 2: 
`(mg/server-address("localhost"))` should be `(mg/server-address "localhost")`.
- Then I tried this with monger `3.1.0`:

```clj
(let [connection (mg/connect
                     (mg/server-address "localhost")
                     (mg/mongo-options {:write-concern WriteConcern/MAJORITY}))
        database (mg/get-db connection "db-name")]
    (prn (.getWriteConcern database)))
; prints:
; #object[com.mongodb.WriteConcern 0x908cab5 "WriteConcern{w=majority, wTimeout=null ms, fsync=null, journal=null"]
```
So it seems to work properly to me.

**Comment by Freezystem** [comment]
@michaelklishin, @leoshaw can we close this issue as it's a requirement for 3.2.0 release ?

**Comment by leoshaw** [comment]
Apologies I'm not currently working with Clojure so can't easily confirm; is it possible it was fixed by other changes?
