### ISSUE TITLE
connect-via-uri throws a NullPointerException when URI doesn't contain a database

### ISSUE THREAD

**Issue by bsiver** [michaelklishin/monger#155]
According to the [Mongo connection string spec](https://docs.mongodb.com/manual/reference/connection-string/), specifying a database in a connection URI is optional.  When I try to use monger's `connect-via-uri` with a URI that does not contain a database, I get a NullPointerException.

e.g.
```
(require '[monger.core :refer [connect-via-uri]])
(connect-via-uri "mongodb://localhost")
```
Results in:
```
NullPointerException   [trace missing]
user=> *e
{:cause nil, 
 :via [{:type java.lang.NullPointerException, :message nil}], 
 :trace []} 
```

**Comment by terjedahl** [comment]
The spec says: "If /database is not specified and the connection string includes credentials, the driver will authenticate to the admin database."
So one might infer that it isn't really optional unless you actually want to authenticate and connect to your admin database.

I, therefore, suggest that this isn't a bug in Monger, but rather a bad handling and exception message form the "com.mongodb" package.

**Comment by michaelklishin** [comment]
Not specifying a database seems to be asking for trouble. Supporting it in a client is therefore not a particularly wise idea.
