### ISSUE TITLE
Cant figure out what  the 'm'  in the query methods are

### ISSUE THREAD

**Issue by rishin4u** [michaelklishin/monger#159]
The [documentation](http://clojuremongodb.info/articles/querying.html#monger_query_dsl) seem to suggest the methods accept one param. Looks like that is not the case
```
(defn find
  [m query]
  (merge m { :query query }))

(defn fields
  [m flds]
  (merge m { :fields flds }))

```

**Comment by michaelklishin** [comment]
`m` means "map", there's a pretty widely used Clojure community convention for when you don't have a more suitable name.

Those functions are not meant to be used on their own but rather a part of the query DSL. Internally "higher up" DSL elements [pipe a map through such functions](https://github.com/michaelklishin/monger/blob/master/src/clojure/monger/query.clj#L179) to produce a final map that is passed on to a function that actually performs the query.
