### ISSUE TITLE
Keys with slashes are not properly saved

### ISSUE THREAD

**Issue by jaor** [michaelklishin/monger#161]
If one tries to insert in a collection a value such as `{:a/b 3}`, the value `{:b 3}` gets saved instead.  That's because `monger.conversion/ConvertToObject` is implemented for keywords as `(.getName input)`, which, i think, is wrong.  Something like `(subs (str input) 1)` would do the right thing.

**Comment by michaelklishin** [comment]
A more common way of doing what you suggest is

``` clojure
(str (namespace :a/b) "/" (name :a/b))
```

Keywords "with slashes" are namespaced. Their serialisation was discussed and considered before.
Serialising them is trivial. Loading them back (telling a namespaced keyword from a string with slashes, for instance) and interoperability is the tricky part.

MongoDB doesn't have the concept of namespaced keys and neither do other languages. I'm not aware of a good strategy to make this interoperate with other languages and not keen on implementing something "OK at best."

**Comment by jaor** [comment]
thanks for your answer.  you just closed the bug.  since i have a production user case where this problem affects my user (i cannot tell them that they shouldn't use slashes in their JSON inputs, since a slash i perfectly okay in JSON), i just wanted to confirm that the decision is simply to keep things as they are for the foreseeable future.  thanks.

**Comment by bandoos** [comment]
Hi, 
I made for my personal use a fork where I use (str (.getNamespace kw) "/" (.getName kw)) 
to work with qualified keywords and monger. 
@michaelklishin  Are you interested in a pr?

**Comment by michaelklishin** [comment]
@bandoos encoding such keywords is trivial. Decoding them is hard, or rather impossible to do deterministically without using a complicated format.

You never know if a slash is the separator or a part of the namespace or the actual name. In `a/b/c`, what is the namespace part and what is the name? No one knows.

**Comment by michaelklishin** [comment]
To answer some earlier questions, the reason why this hasn't been addressed is covered in the ambiguity in decoded values (see above). I don't want to introdue overly smart or opinionated translation layers. Those who must use namespaced keywords can encode and decode them any way they see fit, without creating confusion and unintended side-effects for other Monger users.

I choose interoperability and predictability over support for one Clojure-specific and rarely needed language features. I think it's a reasonable choice. A small library on top of Monger can address this limitation but such feature, if built in, cannot be "taken out".
