### ISSUE TITLE
Time to release 3.2.0?

### ISSUE THREAD

**Issue by oconn** [michaelklishin/monger#165]
Hey @michaelklishin, 

Want to start off with saying thanks for your work on Monger. I was curious when / if there would be a new release to clojars containing the mongodb 3.6.x java driver updates that are on master?

Thanks again,
oconn

**Comment by michaelklishin** [comment]
I'd like to address #146 and move to a GA version of the Java client first. Contributions are welcome.

**Comment by oconn** [comment]
Great, I may have some capacity to look into that this week.

**Comment by a613** [comment]
Should also bump version of mongo driver because only the latest one (`3.6.3`) has support for ssl

**Comment by a613** [comment]
Hi, in addition to bumping the driver version, 3.2.0 would also fix the warning about `any?`, so it's a +1 from me. Almost 2 years since 3.1.0!

**Comment by Freezystem** [comment]
Hi everyone! 
AFAIK #146 seems not to be an issue in `3.1.0` and mongo drivers have finally moved to GA. 
Can we consider moving to `3.2.0` now ? 
I have made the PR that bump mongo drivers to GA.

**Comment by a613** [comment]
@michaelklishin 😢

**Comment by michaelklishin** [comment]
The next release will be 3.5 due to breaking changes in MongoDB server, Java client, CLI tools/admin commands, Ragtime, and core.cache. None of them are major but nonetheless I don't think it's a good idea to use a regular minor version bump. I will file a separate issue about that.
