### ISSUE TITLE
Calling insert-batch with an empty document list causes future ops to hang

### ISSUE THREAD

**Issue by tkocmathla** [michaelklishin/monger#166]
A [bug in the Mongo java driver](https://jira.mongodb.org/browse/JAVA-2434) causes the database handle to hang if an insert is called with an empty list. This is also a problem for the `insert-batch` fn in monger:

```clojure
user=> (require '[monger.collection :as mc])
nil
user=> (mc/insert-batch db "coll" [])

java.lang.IllegalArgumentException: state should be: count
user=> (mc/insert db "coll" {:foo 1})
; hangs...
```

We have worked around this writing a wrapper fn that encloses calls to `insert-batch` with a `(when (seq documents) (mc/insert-batch ...))`. 

Would some kind of similar check be appropriate to add to monger? I don't know if it would be more appropriate within monger to return nil or throw an exception in this case.

**Comment by michaelklishin** [comment]
@tkocmathla is this still relevant in master with an updated MongoDB Java client version? Honestly, I don't think Monger should work around Java client bugs unless they are really severe. We should keep up-to-date with Java client releases instead.
