### ISSUE TITLE
The DBRef and @derefer the DBRef doesn't work

### ISSUE THREAD

**Issue by debian001** [michaelklishin/monger#168]
I follow the [test code](https://github.com/michaelklishin/monger/blob/master/test/monger/test/inserting_test.clj#L111) of derefer a DBRef object, it doesn't work on v3.3.0 as the "The DBRef doesn't implement future interface".

**Comment by debian001** [comment]
If there's a plan, when will DBRef will be supported?

**Comment by michaelklishin** [comment]
There is a [comment that has been around for a few years](https://github.com/michaelklishin/monger/blob/master/test/monger/test/inserting_test.clj#L98). There is no known way of doing that. If you find one in the Java MongoDB client, feel free to leave a comment.

**Comment by michaelklishin** [comment]
In case it isn't clear the test in question is commented out.
