### ISSUE TITLE
WARNING with Clojure 1.9.0

### ISSUE THREAD

**Issue by ikitommi** [michaelklishin/monger#169]
```clj
WARNING: any? already refers to: #'clojure.core/any? in namespace: monger.collection, being replaced by: #'monger.collection/any?
```

**Comment by michaelklishin** [comment]
Feel free to submit a PR.

**Comment by danhut** [comment]
Hi Michael - We are seeing this too - but I thought you had fixed it via this PR already a year ago?
https://github.com/michaelklishin/monger/pull/154

I am happy to do a PR but not understanding why it is needed since your fix looks to still be there.

**Comment by danhut** [comment]
Never mind ... 3.1.0 was pushed to clojars in 2016 and the fix is from 2017.

**Comment by slipset** [comment]
So the problem here is that a new release needs to be cut in order for the relevant commit to be accessible.
