### ISSUE TITLE
Support for $setIsSubset query

### ISSUE THREAD

**Issue by sushanthkumarm** [michaelklishin/monger#184]
This support is essential for managing set operation. It would really helpful if we add this feature.

**Comment by michaelklishin** [comment]
@sushanthkumarm you are welcome to contribute what is missing, Monger is open source software after all.

I don't see anything that would be lacking for [running setIsSubset queries](https://docs.mongodb.com/manual/reference/operator/aggregation/setIsSubset/) besides a missing [operator](https://github.com/michaelklishin/monger/blob/master/src/clojure/monger/operators.clj) which is optional (just [use a string](http://clojuremongodb.info/articles/querying.html#using_mongodb_query_operators)).
