### ISSUE TITLE
Improve developer experience by avoiding "Unresolved var" warnings by clj-kondo

### ISSUE THREAD

**Issue by jacobemcken** [michaelklishin/monger#218]
Since all operators are created using the macro `defoperator` in the `monger.operators` namespace, the IDE doesn't know that these symbols actually exists (and clj-kondo complains about stuff like `Unresolved var: $inc`).

Would you be interested in a PR that declares all operators, kinda like so:
```clojure
(declare $gt $gte $lt $lte ...
...
(defoperator $gt)
(defoperator $gte)
(defoperator $lt)
(defoperator $lte)
...
```

This ensures symbols can be seen by the IDE to improve the developer experience (e.g. easily noticing a typo in an operator).

**Comment by michaelklishin** [comment]
Sure, why not. Thank you.

**Comment by Deraen** [comment]
This and #210 would be indeed nice to improve dev experience with clj-kondo.
