### ISSUE TITLE
unknown top level operator: $ne

### ISSUE THREAD

**Issue by lkrubner** [michaelklishin/monger#87]
Is the documentation out of date for the operators? If I look here: 

https://github.com/michaelklishin/monger/blob/master/src/clojure/monger/operators.clj

I see this example offered in comments:

``` clojure
;; EXAMPLES:
;;   (monger.collection/find "libraries" {$ne { :language "Clojure" }})
```

If I require monger in my own name space with:

``` clojure
  (:require
   [monger.operators :as op]
```

and try:

``` clojure
 (monger.collection/find "Attendance" {op/$ne { :attendance_code "Present" }})
```

I get: 

```
com.mongodb.MongoException: Can't canonicalize query: BadValue unknown top level operator: $ne ("Attendance" {:attendance_code "Present"})
```

Note: before anyone criticizes me on the grounds of style, I will say that :attendance_code has an underscore in it because it holds data imported from a MySQL database.

**Comment by ravinegi007** [comment]
I need help it's very urgent actually I am using MongoDB as a DB and there is a query required where I need to put condition $ne, but it is showing the error consistently (Message: bad query: BadValue: unknown top-level operator: $ne
)
My sample code for idea:
$whereCondition				=	array(array('status'=>'A'));
$whereCondition2				=	array(array('property_verified','P'));

array('$match'=>array('$and'=>$whereCondition,'$ne'=>$whereCondition2)),

till $and condition its working properly but when adding $ne condition its is throwing same above mentioned error.
My mongo shell version is: 3.2.22

Thanks in advance 
Please help
