### ISSUE TITLE
Async API?

### ISSUE THREAD

**Issue by robinheghan** [michaelklishin/monger#94]
Any thoughts on supporting an async api, either using core.async directly or through the use of callbacks?

**Comment by Skinney** [comment]
From what I understand, the latest MongoDB Java driver supports an asynchronous api. When #97 is done, then this should perhaps be looked into? Simply adding a callback api would be best I think, then people could add core.async or manifold or whatever they please.

**Comment by kevinludwig** [comment]
+1 
http://mongodb.github.io/mongo-java-driver/3.0/driver-async/

**Comment by keeth** [comment]
+1

**Comment by michaelklishin** [comment]
@keeth I will open a new issue.
