### ISSUE TITLE
Move to MongoDB Java client 3.0.x

### ISSUE THREAD

**Issue by michaelklishin** [michaelklishin/monger#97]

**Comment by ebaxt** [comment]
Hi @michaelklishin 

Is this a large change? Would love to move to WiredTiger and get away from collection level locking, but from what I've read this requires the latest 3.0 client.

**Comment by michaelklishin** [comment]
@ebaxt moderate: the API has changed quite a bit in some areas, I'm halfway done but have been swamped at work.

**Comment by michaelklishin** [comment]
This is done. I'll file another issue about updating docs and cutting a release.
